### ISSUE TITLE
Not compatible with RF 3.0.4

### ISSUE THREAD

**Issue by andyjmc** [datakurre/robotkernel#10]
ImportError: cannot import name 'TEST_EXTENSIONS' from 'robot.parsing'

**Comment by andyjmc** [comment]
Sorry missed the "Robot Framework 3.1b1 or later."

**Comment by datakurre** [comment]
Actually, I did the change accidentally first and only updated requirements once I run into this myself :( This was required for adding ipynb-parser into RF from outside RF.
