### ISSUE TITLE
Syntax highlighting does not work on JupyterLab

### ISSUE THREAD

**Issue by datakurre** [datakurre/robotkernel#5]
Jupyter Lab: https://mybinder.org/v2/gh/datakurre/robotkernel/master?urlpath=lab/tree/example.ipynb

So extension is not yet complete https://github.com/datakurre/robotkernel/tree/master/src/jupyterlab_robotmode

**Comment by bollwyvl** [comment]
It looks like your mode is registering, as it can be used with a plain text file:
![screenshot from 2018-09-23 10-43-31](https://user-images.githubusercontent.com/45380/45929289-8b7d4680-bf1d-11e8-9140-6e406d190f04.png)

But there is probably a mismatch between what comes back in the `kernel_info` message `codemirror_mode: robotframework` and the declared name, for whatever reason... maybe try `Robot Framework`? I don't have access to my closed code right now, but i think i had to do something like that...

**Comment by datakurre** [comment]
@bollwyvl Thanks for the hint. It was the mismatch in name.

**Comment by bollwyvl** [comment]
Hooray!
